#!/bin/sh
custom=$(dirname $(realpath $0))

cleanup(){
	rm -f $tmp
}
trap cleanup EXIT
tmp=/tmp/customsbo.$$

for i in $(find $custom -type d ! -name .git ! -empty -mindepth 1 -maxdepth 1 -printf "%f\n"); do
	p=$(find /var/lib/sbopkg/SBo-git -type d -name $i)
	[ "$p" = "" ] && continue
	patch=
	for f in $(find $custom/$i ! -name README.md -mindepth 1 -maxdepth 1 -printf "%f\n"); do
		if [ -d $custom/$i/$f ]; then
			if [ -d $p/$f ]; then
				for g in $(find $custom/$i/$f -type f -mindepth 1 -maxdepth 1 -printf "%f\n"); do
					if [ -f $p/$f/$g ]; then
						diff $custom/$i/$f/$g $p/$f/$g || echo "$p/$f/$g already exists and different from $custom/$i/$f/$g"
					else
						cp -a $custom/$i/$f/$g $p/$f
						echo "$p/$f/$g copied"
					fi
				done
			else
				cp -a $custom/$i/$f $p
				echo "$p/$f copied"
			fi
			continue
		elif [ -f $p/$f ]; then
			diff $custom/$i/$f $p/$f || echo "$p/$f already exists and different from $custom/$i/$f"
		else
			cp -a $custom/$i/$f $p
			echo "$p/$f copied"
		fi
		echo $f | grep -q "\.patch$" || continue
		grep -q $f $p/$i.SlackBuild && continue
		pat="patch -p0 < \$CWD/$f"
		if [ "$patch" = "" ]; then
			patch="$pat"
		else
			patch="$patch\n$pat"
		fi
	done
	[ -f $p/$i.SlackBuild.sbopkg -o "$patch" = "" ] && continue
	sed "/^cd \$PRGNAM-\$VERSION/a \\$patch" $p/$i.SlackBuild > $p/$i.SlackBuild.sbopkg
	echo "$p/$i.SlackBuild.sbopkg created with patches"
done
